output "service_account_id" {
  description = "ID of the Terraform service account"
  value       = yandex_iam_service_account.terraform_sa.id
}

output "bucket_name" {
  description = "Name of the S3 bucket"
  value       = yandex_storage_bucket.terraform_state.bucket
}

output "access_key" {
  description = "Static access key for S3 (generated by Terraform)"
  value       = yandex_iam_service_account_static_access_key.sa_static_key.access_key
  sensitive   = true
}

output "secret_key" {
  description = "Static secret key for S3 (generated by Terraform)"
  value       = yandex_iam_service_account_static_access_key.sa_static_key.secret_key
  sensitive   = true
}