[bastion]
bastion-host ansible_host=93.77.176.243 ansible_user=ubuntu ansible_ssh_private_key_file=/home/admin/.ssh/diplom_cloud ansible_ssh_common_args='-o StrictHostKeyChecking=no -o IdentitiesOnly=yes'
       
[master]
k8s-master ansible_host=10.50.0.26

[workers]
k8s-worker-1 ansible_host=10.50.1.18
k8s-worker-2 ansible_host=10.50.2.19

[k8s_cluster:children]
master
workers

[master:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/admin/.ssh/diplom_cloud
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o ProxyJump=bastion'

[workers:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/admin/.ssh/diplom_cloud
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o ProxyJump=bastion'
