[bastion]
bastion ansible_host=51.250.15.241 ansible_user=ubuntu ansible_ssh_private_key_file=/home/admin/.ssh/diploma_cloud

[master]
k8s-master ansible_host=10.10.0.26

[workers]
k8s-worker-1 ansible_host=10.10.1.10
k8s-worker-2 ansible_host=10.10.2.5

[k8s_cluster:children]
master
workers

[master:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/admin/.ssh/diploma_cloud
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@51.250.15.241'

[workers:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/admin/.ssh/diploma_cloud
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@51.250.15.241'
